### ISSUE TITLE
Migration from 1.2 to 1.3 : error: 'x509_cert' has no member named 'rsa'

### ISSUE THREAD

**Issue by repzilon** [polarssl/polarssl#150]
I am trying to migrate a program from PolarSSL 1.2.x to 1.3.x , which does use the deprecated functions. However, it was using the rsa field in x509_cert structure and nothing is mentioned about it in the migration guide. What can I do?

**Comment by pjbakker** [comment]
That's probably because you are using an internal structure field. We have not described all in the migration document.

What happened between 1.2 and 1.3 is that the specific RSA context was replaced with the generic PK context.. You will have to use that one to get to the data you apparently want to access.

**Comment by mpg** [comment]
In addition to what Paul say, you might want to use `pk_rsa()` to access the RSA context inside the PK context. Alternatively, depending on your use case, you may prefer to use the PK interface all the way, which is probably more future-proof.
