### ISSUE TITLE
cann't specific mac_key+aes_key used to decrypt tls session ticket

### ISSUE THREAD

**Issue by byronhe** [polarssl/polarssl#153]
looks like  key_name+aes_key+mac_key is generated randomly in each ssl_set_session_tickets,  there is no way to specific which key_name+aes_key+mac_key to use  for decrypt a ticket.
so cannot resume ticket when the client send old ticket to server.

in ssl_parse_ticket(), the ssl->ticket_keys should  be selected according to key_name,
i advice add a interface like SSL_CTX_set_tlsext_ticket_key_cb() in openssl (https://www.openssl.org/docs/ssl/SSL_CTX_set_tlsext_ticket_key_cb.html)
to let the user choose : 1. encrypt key_name+aes_key+mac_key  2. decrypt   aes_key+mac_key.

**Comment by mpg** [comment]
Indeed. This is already planned for a future release.

**Comment by byronhe** [comment]
i hacked the code  to provide such a interface , i will sent a pull request. 
do you have some advice?

**Comment by mpg** [comment]
We probably won't include a new API for that now, because once we introduce an API we try to keep it stable for a while. Also, for the same kind of reason, we can't quite change the API in the 1.3 branch enough to implement a clean solution.

However we might publish a workaround as Knowledge base article or even an example program, so if you found a workaround and would like to share it, that would be very much appreciated.
