### ISSUE TITLE
cert_write creates certificates with signature algorithm "sha1"

### ISSUE THREAD

**Issue by thenktor** [polarssl/polarssl#163]
Hi,
I've just tried to create self-signed certificates as shown in this how-to: https://polarssl.org/kb/how-to/generate-a-self-signed-certificate

Sadly the created certificates use the signature algorithm "sha1WithRSAEncryption". AFAIK nowadays this one should not be used anymore. Instead "sha256WithRSAEncryption" should be used.

Also see this Google blog entry: http://googleonlinesecurity.blogspot.de/2014/09/gradually-sunsetting-sha-1.html

**Comment by mpg** [comment]
Indeed we forgot to update this (hardcoded) default in the programs, thanks for noticing and letting us now! I just fixed that (and all other example programs using signatures) internally.

Note however that in the special case of a self-signed certificate, there is not security issue, since the trust in the certificate is not based on the self-signature anyway and has to be established via another channel (user action, dane, tofu, device provisioning, etc).

PS: we would like to credit you in the Changelog for noticing the issue, what name should we use for that?

**Comment by thenktor** [comment]
Indeed it does not matter for the self signed cert itself :) My name is Thorsten Mühlfelder.
