### ISSUE TITLE
Uninitialized variable in rsa_public()

### ISSUE THREAD

**Issue by juengst** [polarssl/polarssl#166]
In rsa.c, the function rsa_public() tests a variable "ret" which was never initialized.  This could cause false failures of this function.

**Comment by mpg** [comment]
I disagree, the variable `ret` is initialized inside the macro `MPI_CHK`.

As a general rule, since we compile with a pretty high level of warnings (`-Wall -Wextra -O1` and then some more) it's quite unlikely that an obviously uninitialized variable would not immediately flagged by the compiler. In addition, we run tests with either valgrind's memcheck or clang's memsan, which would catch it at runtime too. Not to mention static analyzers :)
