### ISSUE TITLE
tls handshake very slow

### ISSUE THREAD

**Issue by jkarneges** [polarssl/polarssl#168]
Hi,

I'm using mongrel2 with polarssl 1.3. Earlier I was using 1.3.0, and a few days ago I updated polarssl to 1.3.10. Since the update, I've observed that TLS handshakes seem to be at least 3x slower, and I have a feeling that some blocking code in polarssl is causing extra trouble for mongrel2's single-threaded event-driven engine (based on libtask).

Sorry for not having too many details yet, I'm investigating further now, but I just wanted to throw this out there in case anyone had a tip that could help my investigation. For example, maybe in some revision over the past year, some anti-timing attack code was added to polarssl that uses excess cpu? Thanks.

**Comment by jkarneges** [comment]
Binary search narrowing things down. 1.3.1 is fast for me and 1.3.2 is slow. Commit history between 1.3.1 and 1.3.2 shows a bunch of "constant time" changes. Maybe this is the reason.

**Comment by jkarneges** [comment]
Seems 3f917e230df049fc2ea5269348ca53b0a3ba6edc is the culprit.

**Comment by jkarneges** [comment]
False alarm. Mongrel2 was using an old copy of polarssl's config.h file. I copied over the latest and merged the original changes and now it runs fast again!

**Comment by mpg** [comment]
Glad it's solved! And thanks for doing all the hard investigation work :)

In order to avoid this kind of issue in the future, I would recommend that, instead of manually maintaining the `config.h` changes, you have a script that applies the needed changes (it will probably consist of simple invocations of `scripts/config.pl`), so that each time you upgrade ~polarssl~ mbed TLS you can start from the updated `config.h` and apply your script to it. This should allow you to get the new things while preserving your changes.

We want to make life as easy as possible for people using custom configs, so feel free to comment and suggest improvements!
