### ISSUE TITLE
AES GCM C code

### ISSUE THREAD

**Issue by Tinto1990** [polarssl/polarssl#176]
Hi,

I'm working in wipro technologies. As part of my project i have to implement AES GCM encryption model.
I'm planning to use your AES GCM C code. I have few doubts regarding the code.
1.is it 256 byte encryption?
2.How to use this c code? which task i should call?

Regards,
Tinto

**Comment by mpg** [comment]
Hi,

I think this kind of question is better asked on the support forum: https://polarssl.org/discussions
You should only open an issue here when you think there is a fault in the code and/or want to suggest an improvement.

I'll reply on the forum if you post there, I prefer not to reply here in order to avoid cluttering the conversation.
